name: executable-notebook-template
channels:
  - conda-forge
dependencies:
  - pandas
  - numpy
  - jupyterlab=3
  - matplotlib-base>=2.2.2
  - ipympl=0.6.3
  - ipywidgets
  - nibabel=3.2.1
  - nilearn=0.7.1